namespace FakeItEasy.Creation
{
    using System;
    using System.Collections.Generic;
    using System.Linq.Expressions;
    using FakeItEasy.Core;

    /// <summary>
    /// An interface to be implemented by classes that can generate proxies for FakeItEasy.
    /// </summary>
    internal interface IProxyGenerator
    {
        /// <summary>
        /// Gets a value indicating whether a proxy for the specified type can be generated by the proxy generator.
        /// </summary>
        /// <param name="typeOfProxy">The type of proxy to generate.</param>
        /// <param name="failReason">The reason the proxy can not be generated. <c>null</c> if the proxy can be generated.</param>
        /// <returns>True if the proxy can be generated.</returns>
        bool CanGenerateProxy(Type typeOfProxy, out string failReason);

        /// <summary>
        /// Generates a proxy of the specified type and returns a result object containing information
        /// about the success of the generation and the proxy if it was generated.
        /// </summary>
        /// <param name="typeOfProxy">The type of proxy to generate.</param>
        /// <param name="additionalInterfacesToImplement">Interfaces to be implemented by the proxy.</param>
        /// <param name="argumentsForConstructor">Arguments to pass to the constructor of the type in <paramref name="typeOfProxy" />.</param>
        /// <param name="attributes">The expressions that describe the attributes to add to the proxy.</param>
        /// <param name="fakeCallProcessorProvider">The call processor provider.</param>
        /// <returns>A result containing the generated proxy.</returns>
        ProxyGeneratorResult GenerateProxy(Type typeOfProxy, IEnumerable<Type> additionalInterfacesToImplement, IEnumerable<object> argumentsForConstructor, IEnumerable<Expression<Func<Attribute>>> attributes, IFakeCallProcessorProvider fakeCallProcessorProvider);
    }
}
