[project]
name = "fakeiteasy"
version = "0.1.0" # value isn't important; we're just building the documentation
requires-python = "~=3.14.0"

[dependency-groups]
dev = [
    "linkchecker",
    "mike",
    "mkdocs",
    "mkdocs-material",
]
