name: build docs

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout FakeItEasy
        uses: actions/checkout@v3
        with:
          submodules: false
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement docs/requirements.txt
      - name: Build docs
        run: python -m mkdocs build --clean --site-dir artifacts/docs --config-file mkdocs.yml --strict
      - name: Upload docs
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: artifacts/docs