name: Build pull request

on:
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true
  DOTNET_GENERATE_ASPNET_CERTIFICATE: false

jobs:

  build-windows:
    name: Build on Windows
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
      - name: Run build script
        run: ./build.cmd
        shell: cmd
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: windows-artifacts
          path: artifacts\**\*

  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: false
      - name: Run build script
        run: ./build.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: ubuntu-artifacts
          path: artifacts/**/*
