name: Test find workflow run
on:
  pull_request:

jobs:
  find-workflow-run:
    name: Find workflow run
    runs-on: ubuntu-22.04
    steps:
      - name: Debug - SHA values
        uses: actions/github-script@v7
        with:
          script: |
            core.info('context.sha: ' + context.sha);
            core.info('github.event.pull_request.head.sha: ${{ github.event.pull_request.head.sha }}')
